# Questions 1

Create a numpy array starting from 2 till 50 with a stepsize of 3.

#### Answer

In [1]:
import numpy as np
arr = np.arange(51)[2:51]
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

# Questions 2

Accept two lists of 5 elements each from the user. <br>
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it

#### Answer

In [2]:
list1 = [1, 8, 3, 5, 4]
list2 = [7, 2, 8, 10, 9]
array_list1 = np.array(list1)
array_list2 = np.array(list2)
concatenate_arrays = np.concatenate((array_list1, array_list2))
print(concatenate_arrays)
concatenate_arrays_sorted = sorted(concatenate_arrays)
print(concatenate_arrays_sorted)

[ 1  8  3  5  4  7  2  8 10  9]
[1, 2, 3, 4, 5, 7, 8, 8, 9, 10]


# Questions 3

Write a code snippet to find the dimensions of a ndarray and its size.

#### Answer

In [3]:
array_list1 = np.array([1, 8, 3, 5, 4])
print("array dimensions is :", array_list1.ndim)
print("array size is :", array_list1.size)

array dimensions is : 1
array size is : 5


# Questions 4

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet <br>
Hint: np.newaxis, np.expand_dims

#### Answer

In [4]:
# np.newaxis
array_1 = np.arange(10)
array_2 = array_1[:, np.newaxis]
print("array_1=", array_1)
print("array_1 dimensions is ", array_1.ndim)
print("array_2=", array_2)
print("array_2 dimensions is ", array_2.ndim)

# np.expand_dims
array_3 = np.arange(8)
array_4 = np.expand_dims(array_3, 0)
print("array_3=", array_3)
print("array_3 dimensions is ", array_3.ndim)
print("array_4=", array_4)
print("array_4 dimensions is ", array_4.ndim)

array_1= [0 1 2 3 4 5 6 7 8 9]
array_1 dimensions is  1
array_2= [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
array_2 dimensions is  2
array_3= [0 1 2 3 4 5 6 7]
array_3 dimensions is  1
array_4= [[0 1 2 3 4 5 6 7]]
array_4 dimensions is  2


# Questions 5

Consider two square numpy arrays. Stack them vertically and horizontally. <br>
Hint: Use vstack(), hstack()

#### Answer

In [5]:
a = np.array([[1,2],[3,4]])
print("a =", a)
print("shape a:", a.shape)
b = np.array([[6,9],[7,8]])
print("b =", b)
print("shape b:", b.shape)

print('Vertical Append:', np.vstack((a, b)))
print('Horizontal Append:', np.hstack((a, b)))

a = [[1 2]
 [3 4]]
shape a: (2, 2)
b = [[6 9]
 [7 8]]
shape b: (2, 2)
Vertical Append: [[1 2]
 [3 4]
 [6 9]
 [7 8]]
Horizontal Append: [[1 2 6 9]
 [3 4 7 8]]


# Questions 6

How to get unique items and counts of unique items?

#### Answer

In [6]:
c = np.array([1,6,2,2,6,2,7,2,6,9,1,4,2,4,2,4,7,2,4,1,4,2])
print(c)
uniqueItems, occurCount = np.unique(c, return_counts=True)
print("There are", len(uniqueItems), "unique items")
print("Unique Items : " , uniqueItems)
print("Occurrence Count : ", occurCount)

[1 6 2 2 6 2 7 2 6 9 1 4 2 4 2 4 7 2 4 1 4 2]
There are 6 unique items
Unique Items :  [1 2 4 6 7 9]
Occurrence Count :  [3 8 5 3 2 1]


In [8]:
# Zip both the arrays
listOfUniqueItems = zip(uniqueItems, occurCount)
print('Unique Items along with occurrence Count')

# Iterate over the zip object
for elem in listOfUniqueItems:
    print(elem[0] , ' Occurs : ' , elem[1], ' times')

Unique Items along with occurrence Count
1  Occurs :  3  times
2  Occurs :  8  times
4  Occurs :  5  times
6  Occurs :  3  times
7  Occurs :  2  times
9  Occurs :  1  times
